env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  import/extensions: 0,
  react/function-component-definition: [
    1, 
    {
      namedComponents: arrow-function,
    }]
}
